name: chatting_app
version: 1.0.0+1
publish_to: none
description: This is chatting app with firebase
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

font: 
  - family: Poppins
    fonts: 
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700

